### ISSUE TITLE
Add skip button

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/desc-exp-checker#10]
It would be good to add a `skip` button to advance to the next image without registering an evaluation of the current image. This ties into a broader question about whether the buttons are intuitive. I've seen several users be confused by the `Next` button.

**Comment by kadrlica** [comment]
I've added a `Skip` button and renamed `Next ` to `Submit`. I'm slightly worried that `Skip` will make it too easy for users to not log their feedback, but hopefully the gamification will overpower that. Feedback welcome from @pmelchior, @esheldon, @SimonKrughoff, @yymao, and @rmandelb.

Live version can be found on:
https://portal-auth.nersc.gov/projecta/lsst/dev-exp-checker/index.html

**Comment by pmelchior** [comment]
In terms of button labelling, I also realized that some users where confused by "Next", so in principle your changes sound better. We didn't care if some people click "Next" even if there were problems in the images as long as we find examples of problems. Complete discovery of all flaws always has never been a design goal, whereas maximum simplicity was.

So the question is: do you distract users more by the distinction between "Skip" and "Submit". And the next question: do you have a use case for "Skip" that makes it worth having a button.

**Comment by kadrlica** [comment]
Having a `Skip` button is extremely useful to me. For training and testing algorithms it is very useful to have a set of images that are actually "good". Having a `Skip` button allows me to quickly flip through images without contaminating my set of "good" exposures. Previously I was doing the skipping by using the checker without logging in. However, with the NERSC authentication that is not a natural option.

I'd be grateful for user feedback on any confusion between `Skip` and `Submit`.

**Comment by kadrlica** [comment]
Closed via #24
