### ISSUE TITLE
incorrect association of where image is in focal plane?

### ISSUE THREAD

**Issue by rmandelb** [LSSTDESC/desc-exp-checker#12]
Hi @kadrlica - 

I was playing around with the exposure checker, and ran into what may be a problem in associating one of the half-CCD images with its position in the focal plane.

I got an image that looks like this:
![image](https://user-images.githubusercontent.com/1454906/36360321-cf02cf2e-14f0-11e8-94dc-2b5627857280.png)

with the following URL: https://portal-auth.nersc.gov/projecta/lsst/desc-exp-checker/viewer.html?release=DC2&expname=v151687-fr&ccd=14-12-A#
(I assume this tells you enough that you can find its info at NERSC?)

So I though it would be useful to see in the context of the full focal plane, because there's apparently something major going on nearby.  I tried the "Show entire FoV option", and here's a screenshot of the result:

![image](https://user-images.githubusercontent.com/1454906/36360309-b395ca02-14f0-11e8-8218-f67775106bdb.png)

I thought the red outline was supposed to be showing me the half-CCD that I'm looking at, but the red outlined part looks quite dark, unlike the image I originally got.  When I click on it, it does take me back to the original image I was looking at.

This seems wrong to me, unless I have misunderstood the intended behavior of the "Show entire FoV option"?

**Comment by kadrlica** [comment]
@rmandelb the feature that you are seeing is the vignetting of the focal plane. I think that you are understanding the behavior of "Show entire FoV" and it is actually doing the right thing. Our FoV PNG has it's y-axis inverted from [this diagram of the LSST FoV](https://confluence.lsstcorp.org/display/LSWUG/Representation+of+a+Camera), which agrees that this CCD should be R14-S12.

I think that what is probably confusing here is that the individual CCDs in the FoV image have their sky background level dynamically scaled. This CCD has been scaled to the bright portion, while it's neighbors have a more reasonable dynamic range. You can see another example of a mis-scaled CCD located two CCDs above this one. @SimonKrughoff might be able to comment on why/how the scaling of the FoV PNG is done.

**Comment by kadrlica** [comment]
If you are interested in the downsampled half-CCD image on NERSC it can be found here:
/global/projecta/projectdirs/lsst/www/desc-exp-checker/exclusive/binned_sensor_halves/v151687-fr/R14/S12_A.fits

The full binned CCD can be found here:

**Comment by rmandelb** [comment]
OK - thanks - different scalings for CCDs vs. the FoV could easily cause the problem!

I see you opened a new issue to improve the scaling - thanks.

I am only leaving this open in case Simon wants to comment on the full-FoV scaling.

**Comment by kadrlica** [comment]
I'm closing this issue for the time being.
