### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/desc-exp-checker#6]
@ellongley made a great start on this, but we need to go through and update the documentation in more depth. Specifically, the introduction, tutorial, and FAQ need a thorough adjustment/update.

**Comment by rmandelb** [comment]
@kadrlica - would it be worth recruiting a few people for this from the eyeballs slack channel?

**Comment by kadrlica** [comment]
@rmandelb sure! I took a first pass last night in 9bc60c379e1b1696fbd7c93e8845bc158e242aeb, but we still need to copy over the images for the tutorial. In addition combing through for any DECam specific references would be great.

The longer and larger task is to assemble a note detailing the types of problems that are found in the simulated images. This will be the product of the exposure checking, but will also feed back into the problem classes that we document with the tool. In this way, the exposure checker documentation is in a constant state of improvement as new problem classes come and go.

**Comment by kadrlica** [comment]
Large steps forward were made with #19.
