### ISSUE TITLE
Access images via native directory

### ISSUE THREAD

**Issue by kadrlica** [LSSTDESC/desc-exp-checker#8]
Currently we need to copy the downsampled images into the exposure checker directory. We would prefer to be able to symlink to the native directory on `projecta` instead. We are iterating with NERSC support (INC0115288) on this.

**Comment by yymao** [comment]
The backend code should be able to access any files on projecta, as long as those files have `o+r`.  Symlink is not required.

**Comment by kadrlica** [comment]
Interesting, let me check...

**Comment by kadrlica** [comment]
Ok, it looks like this is a permissions issue. Changing issue title.
